__NAME: Duo ZHOU__

__NETID: duozhou2__

# Question 1

Show that a directed graph G is acyclic if and only if we can renumber its nodes so that its node-node adjacency matrix is a lower triangular matrix.

## Solution

__Proof:__ A directed graph G is acyclic if and only if there are no directed cycles in the graph.

First, let's prove that if G is acyclic, we can renumber its nodes so that its node-node adjacency matrix is a lower triangular matrix.

An acyclic directed graph can be topologically sorted, which means that the nodes can be renumbered such that for every directed edge $(u, v)$, node $u$ appears before node $v$ in the ordering. 

$\because$ If there is an edge $(u, v)$ and $u$ is assigned a lower number than $v$, then the entry in the adjacency matrix for the edge $(u, v)$ will be in a lower row and column than the entry for the edge $(v, u)$ (if it exists).

$\therefore$ If we use this topological ordering as the new numbering of the nodes, the node-node adjacency matrix will be a lower triangular matrix. 

If the adjacency matrix of a graph is lower triangular, $\to$ there is no edge from a node with a higher number to a node with a lower number, $\to$ there are no directed cycles in the graph, and therefore the graph is acyclic.

$\therefore$ A directed graph G is acyclic if and only if we can renumber its nodes so that its node-node adjacency matrix is a lower triangular matrix.

# Question 2

Let $M$ denote the node-node adjacency matrix of a network $G$. Show that $G$ is strongly connected if and only if the matrix $M+ M_2 + M_3 + ... + M_n$ has no zero entry, for some integer $n$.

## Solution

__Proof:__


Lemma 1: A graph $G$ is strongly connected if there exists a path from every vertex to every other vertex. 

Lemma 2: The adjacency matrix $M$ of a graph $G$ represents the edges between the vertices, where the entry $M_{i,j}$ is 1 if there is an edge from vertex $i$ to vertex $j$, and 0 otherwise.

$\because$ The matrix $M^k$ for $k\geq 1$ represents the paths of length $k$ between the vertices. $\therefore$ If there exists an entry $M^k_{i,j} = 1$, it means that there is a path of length $k$ from vertex $i$ to vertex $j$.

The sum of matrices $M + M^2 + M^3 + ... + M^n$ represents all possible paths of length 1, 2, 3, ..., $n$ between vertices. If all entries of the sum are non-zero, it means that there exists a path between every vertex and every other vertex, and therefore the graph is strongly connected.

Conversely, if the graph is strongly connected, there exists a path between every vertex and every other vertex. Hence, for any $n$, there will always exist a path of length $n$ between every vertex and every other vertex, which means that all entries of the sum $M + M^2 + M^3 + ... + M^n$ will be non-zero.

$\therefore$ A graph $G$ is strongly connected if and only if the matrix $M + M^2 + M^3 + ... + M^n$ has no zero entry for some integer $n$.

# Question 3

Consider an undirected network with an origin, a destination, and 100 additional nodes, with each pair of nodes connected by an arc. Show that the number of different paths from origin to
destination is given by

$$\begin{pmatrix} 100 \\ 0 \end{pmatrix} 100! +\begin{pmatrix} 100 \\ 1 \end{pmatrix} 99! +\begin{pmatrix} 100 \\ 2 \end{pmatrix} 98!+...+\begin{pmatrix} 100 \\ 98 \end{pmatrix} 2!+\begin{pmatrix} 100 \\ 99 \end{pmatrix} 1!+\begin{pmatrix} 100 \\ 100 \end{pmatrix} 0!$$

# Question 4

Show that every tree forms an undirected bipartite graph. Does every undirected bipartite graph form a tree, prove or give a counter example?

# Programming Question:
For this part of the homework, you will implement some of the algorithms learnt in class. You may use Python, C++, or Java to execute this (Prefer C++ as it will be helpful with CUDA later). Custom packages cannot be used to replace the algorithms tested. The dataset for this can be downloaded from here. This source contains an undirected graph with 112 nodes and 425 edges. 

## a. Store the graph in adjacency matrix form.

In [83]:
import numpy as np
import pandas as pd

df = pd.read_table('./adjnoun_adjacency/out.adjnoun_adjacency_adjacency', sep=" ", names = ["node", "edge","NA","NA1"], index_col=None)
df = df.drop(index=[0,1], columns=["NA","NA1"])
df["w"]=df[["node", "edge"]].apply(lambda x: abs(int(x["node"]) - int(x["edge"])), axis=1)
df = df.to_numpy().astype(int)

In [95]:
df                   

array([[  1,   2,   1],
       [  1,   3,   2],
       [  1,   9,   8],
       ...,
       [104, 105,   1],
       [105, 106,   1],
       [106, 109,   3]])

In [96]:
graph1 = np.zeros((112,112))
for i in range(df.shape[0]):
    graph1[df[i,0]-1,df[i,1]-1] = 1

graph1

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])


## b. Is this graph connected? What is the median degree of the nodes?



In [44]:
n_entrys = 0
id_nodes =[]
for i in range(graph1.shape[0]):
    n_entrys += sum(graph1[i])
    id_nodes.append(sum(graph1[i]))

if n_entrys == 425:
    print(f'This graph is connected. The median degree of the nodes is {np.median(id_nodes)}')
else:
    print('This graph is NOT connected')

    

This graph is connected. The median degree of the nodes is 2.0


## c. Using the adjacency matrix, write a program to compute the number of triangles. 

Note: A triangle is a connected subgraph of size three.

In [45]:
np.linalg.matrix_power(graph1,3).trace()/6

0.0

To set up instance of minimum spanning tree, add edge costs using the following procedure. For an edge between nodes with indices $i$ and $j$, let $|i-j|$ be its edge cost. For example, the cost associated with edge $(31,17)$ is 14. Using this modified graph:




In [55]:
MAX=1e6
graph2 = np.full_like(graph1, MAX )
for i in range(df.shape[0]):
    graph2[df[i,0]-1,df[i,1]-1] = abs(df[i,0] - df[i,1])

In [56]:
graph2

array([[1.00e+06, 1.00e+00, 2.00e+00, ..., 1.00e+06, 1.00e+06, 1.00e+06],
       [1.00e+06, 1.00e+06, 1.00e+00, ..., 1.00e+06, 1.00e+06, 1.00e+06],
       [1.00e+06, 1.00e+06, 1.00e+06, ..., 1.00e+06, 1.00e+06, 1.09e+02],
       ...,
       [1.00e+06, 1.00e+06, 1.00e+06, ..., 1.00e+06, 1.00e+06, 1.00e+06],
       [1.00e+06, 1.00e+06, 1.00e+06, ..., 1.00e+06, 1.00e+06, 1.00e+06],
       [1.00e+06, 1.00e+06, 1.00e+06, ..., 1.00e+06, 1.00e+06, 1.00e+06]])

## d. Implement the Kruskal’s algorithm to find the minimum spanning tree.

## e. Implement the Prim’s algorithm to find the minimum spanning tree.



## f. Report the performances for each algorithm (running time, optimal cost, and the optimal solution). Why is there a difference in the run time?


## g. Formulate the minimum spanning tree problem as a polynomial sized mixed integer linear program (MILP).



## e. For the given graph instance, solve the MILP formulation using a commercial solver of your choosing, and report the results (running time, optimal cost, and the optimal solution). How does this compare with part f?